### ISSUE TITLE
[Feature] The ability to change the icons to black for white theme

### ISSUE THREAD

**Issue by QkeleQ10** [evilpro/Taskplay#9]
![image](https://user-images.githubusercontent.com/55982900/69426062-8b005b80-0d2c-11ea-9abe-ea7752c08aa3.png)
That does not look amazing, does it?

**Comment by rlad78** [comment]
@evilpro if you're still working on project, it'd be amazing to see this feature added.

**Comment by ogustbiller** [comment]
> @evilpro if you're still working on project, it'd be amazing to see this feature added.

Please 🙏
